version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: schedulemaker_local
    ports:
      - "4567-4584:4567-4584"
      - '8055:8080'
    environment:
      - SERVICES=s3,dynamodb,lambda,iam,apigateway,cloudwatch
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './localstack:/tmp/localstack'
