version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: awslocal
    ports:
      - "4567-4586:4567-4586"
      - '8055:8080'
    environment:
      - SERVICES=s3,dynamodb,lambda,iam,apigateway,cloudwatch
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_DOCKER_NETWORK=host
    volumes:
      - '~/localstack:/tmp/localstack'
      - /var/run/docker.sock:/var/run/docker.sock
